### PR TITLE
Do not use inputs.txt

### PR DESCRIPTION
**Pull request by snus-kin**
This also allows for filenames with characters that would break program to work 
e.g. "10 Travelin' Jam.flac"

### CODE REVIEW

**Comment by MartinBarker** [comment]
will review this weekend thank you

**Comment by snus-kin** [comment]
Thanks, made some changes on my fork also that I won't make a PR because it changes functionality but you might be interested in looking at, just more options and making ffmpeg quieter mostly.

**Comment by MartinBarker** [comment]
Thanks I'll take a look, making ffmpeg quieter is definitely a plus. This repo is honestly pretty out-dated, I haven't touched it in a while. I've been working moreon my pip3 package commandLineMusicVideo which does the same thing [https://github.com/MartinBarker/commandLineMusicVideo] but it does just run ffmpeg commands similar to this bash fie. maybe ill move this bashAlbumExporter into an apt-get package for easier download

ill take a look at your fork tho, thanks again

**Comment by snus-kin** [comment]
Yeah no worries I just find this personally useful so I thought I'd make a PR to at least fix the broken bit w/ FLAC files. I like that it's just a bash file! No need to package it imo, especially if you have a py version.

**Pull request merged**
